### ISSUE TITLE
Bayesian Optimization Capabilities

### ISSUE THREAD

**Issue by bacalfa** [scikit-learn-contrib/MAPIE#172]
Not an issue, but a few questions.

- Is it possible to use Bayesian optimization (e.g., https://scikit-optimize.github.io/stable/) with a `MapieRegressor` or `MapieClassifier` model?
- If I fit the scikit-learn estimator with Bayesian optimization and pass it to the MAPIE estimator, will the original estimator be refit? What if I want to freeze the scikit-learn estimator?

**Comment by vtaquet** [comment]
Hi @bacalfa , we haven't tested the objects from scikit-optimize but my guess is that `BayesSearchCV` is fully compatible with MAPIE since it has a scikit-learn-compatible API. Be careful though, if I'm not mistaken, `BayesSearchCV` is not compatible with the most recent scikit-learn versions and it could raise some conflicts with MAPIE.

**Comment by vtaquet** [comment]
Hi @bacalfa , have you been able to test whether scikit-optimize is compatible with MAPIE ?

**Comment by vincentblot28** [comment]
As this issue has no activities, I close it. Feel free to re-open it
