### ISSUE TITLE
MapieRegressor has some bug when using other cv (sklearn.model_selection)

### ISSUE THREAD

**Issue by callmedrcom** [scikit-learn-contrib/MAPIE#207]
**Describe the bug**
regression.py line 550  self.residuals_ = np.abs(np.ravel(y) - y_pred) may have 'nan' when use "sklearn.model_selection.TimeSeriesSplit"
**Reason for the bug**
The "TimeSeriesSplit" will not validate the first few samples, this cause error in interval prediction

**Comment by LacombeLouis** [comment]
Hey @callmedrcom, thank you for raising this issue. Could you send us your code so that we can perform the error ourselves and come back to you with a more constructive answer? Thank you!

**Comment by callmedrcom** [comment]
Sorry for the interupt, i have update the package into newest version. This problem seems to be fixed by using np_nanquantile in new version. However, when using TimeSeriesSplit there are still lots of warning. The following are my test code. The waring seems come from the not validated part.

import sklearn
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from mapie.time_series_regression import MapieTimeSeriesRegressor

trainx = np.random.rand(100, 30)
trainy = np.random.rand(100)
testx = np.random.rand(1, 30)
testy = np.random.rand(1)

model = RandomForestRegressor(
    max_depth=10, n_estimators=25, random_state=59
)

cv_ts = sklearn.model_selection.TimeSeriesSplit(n_splits=5)
train_index = []
val_index = []
for train, val in cv_ts.split(trainx):
    train_index.append(train)
    val_index.append(val)
# Time series split will always keep 0~19 as train. in other words val index didnt include N0.0~19 the calculation 
# result remain NAN. 
mapie = MapieTimeSeriesRegressor(
    model,
    method="enbpi",
    cv=cv_ts,
    agg_function="mean",
    n_jobs=-1,
)
# the residual contain nan, i think this should be deleted to avoid warning.
mapie = mapie.fit(trainx, trainy)
y_pred_npfit_enbpi, y_pis_npfit_enbpi = mapie.predict(testx, alpha=0.05)

**Comment by vtaquet** [comment]
Hi @callmedrcom , thanks for raising the issue. The warnings are normal, they are indeed raised because MAPIE assumes that all training points should have been seen as calibration points at least once, like with the jackknife or CV strategies. In fact, `TimeSeriesSplit` should not be used with `MapieTimeSeriesRegressor`, we advise you to use `BlockBootstrap` instead, following this example : https://mapie.readthedocs.io/en/latest/examples_regression/2-advanced-analysis/plot_timeseries_enbpi.html#sphx-glr-examples-regression-2-advanced-analysis-plot-timeseries-enbpi-py. We are working on a more pedagogical tutorial that explains how to use `MapieTimeSeriesRegressor`.
