### ISSUE TITLE
Return ensembled predictions even when alpha is None

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/MAPIE#252]
Hi all, and thanks you so much for developping MAPIE !

I recently hit a limitation of `MapieRegressor` and `MapieTimeSeriesRegressor` : I would like to get the ensembled predictions (using the `ensemble=True` argument in `.predict()`), but without computing any confidence interval. So I used `alpha=None`, but in this case, the `ensemble` argument is ignored, since the code returns immediately the `single_estimator_` predictions.

However, it might be that we still want to extract the ensembled prediction (which is easily available in MAPIE class internals) even when `alpha=None`, given that the computation of this prediction is rather involved.

So it appears that there is an unnecessary coupling between `alpha=None` and the ability to retrieve ensembled predictions.

Would it be possible to decouple these two quite different things ?

**Comment by BaptisteCalot** [comment]
We're good now, the issue is no longer present. We're getting different results between mapie_enbpi.predict(X_test, alpha=None, **ensemble=True**, optimize_beta=True) and mapie_enbpi.predict(X_test, alpha=None, **ensemble=False**, optimize_beta=True), and we're indeed not passing through the same parts of the Ensemble Regressor code
