### ISSUE TITLE
Making MAPIE compatible with Tensorflow 

### ISSUE THREAD

**Issue by nilips70** [scikit-learn-contrib/MAPIE#275]
It would be great if MAPIE could work with Tensorflow deep learning models. I have an LSTM model developed in Tensorflow using Keras API which only gives point forecasts. I would like to have conformal prediction intervals for the forecasts. Is it possible to use MAPIE for it?

**Comment by vincentblot28** [comment]
Hi @nilips70, thank you for your interest in MAPIE. There is one way to make your model compatible with Tensorflow, to do so you need to construct a wrapper around your tf model so that you will have the necessary class attributes and methods to use MAPIE. An exemple is given in this notebook : https://github.com/scikit-learn-contrib/MAPIE/blob/master/notebooks/classification/Cifar10.ipynb
