### ISSUE TITLE
Inconsistent functions in ConformityScore class: seeking explanation

### ISSUE THREAD

**Issue by jesuinovieira** [scikit-learn-contrib/MAPIE#321]
**Describe the bug**

When using `MapieRegressor` to generate prediction intervals, an intermittent error occurs with the following message:

> ValueError: The two functions get_conformity_scores and get_estimation_distribution of the ConformityScore class are not consistent. The following equation must be verified: self.get_estimation_distribution(y_pred, self.get_conformity_scores(y, y_pred)) == y. The maximum conformity score is 3.0517578125e-05. The eps attribute may need to be increased if you are sure that the two methods are consistent.

The cause of this error and its inconsistency is currently unknown.

**To reproduce**

The error occurs approximately 15% of the software runs. Despite multiple attempts to reproduce the error using the provided code, identical data, Python version, and installed packages, the issue could not be replicated. In other words, the error appears to be specific to my software and is not observed in other environments.

```python
import pandas as pd
from mapie.regression import MapieRegressor
from sklearn import linear_model
from sklearn.exceptions import ConvergenceWarning
from sklearn.model_selection import train_test_split
from tqdm import tqdm

data = pd.read_csv("data/autompg.csv")
n = 1000
target = "mpg"

for _ in tqdm(range(n)):
    train, calib = train_test_split(data, test_size=0.25, shuffle=True)

    X_train, y_train = train.drop(columns=[target]), train[target]
    X_calib, y_calib = calib.drop(columns=[target]), calib[target]

    model = linear_model.LinearRegression()
    model.fit(X_train, y_train)

    mapie = MapieRegressor(model, cv="prefit")
    mapie.fit(X_calib, y_calib)
```

**Expected behavior**

I would like to understand the circumstances under which this exception is raised. Additionally, I seek guidance on how to resolve the issue.

**Desktop**
 
 - OS: Ubuntu 20.04.6 LTS
 - MAPIE version: 0.6.4
 - Python 3.7 (although the issue also occurred with 3.10)

**Comment by thibaultcordier** [comment]
Hi @jesuinovieira, thank you for reporting this issue.

# Interest of this exception
This exception has been raised for several reasons. First of all, what is the motivation behind this exception?
- Every `MapieRegressor` object must instantiate a `ConformityScore` object to calculate the non-conformity score (see the conformal prediction theory).
- The method that raises this exception is `check_consistency` in the `ConformityScore` class (see [here](https://github.com/scikit-learn-contrib/MAPIE/blob/master/mapie/conformity_scores/conformity_scores.py#L105)), which checks consistency between the following methods ``get_estimation_distribution`` and ``get_signed_conformity_scores``.
- In other words, it verifies that from the actual target, we can calculate the predicted target based on the non-conformity score and vice-versa without loss of precision (we're checking the bijective property of the method in fact).
- The purpose of this check is to ensure that if a user wants to create a new `ConformityScore`, he must check that his implementation is mathematically consistent (based on the computer precision). This is not the case for you, as you are using the default value proposed by the MAPIE library.

# Particular interpretation of your exception
In your case, this exception tells us that some of your data is having difficulty being recalculated with high precision in the `ConformityScore` object (by default, `MapieRegressor` uses `AbsoluteConformityScore` (see [here](https://github.com/scikit-learn-contrib/MAPIE/blob/master/mapie/conformity_scores/residual_conformity_scores.py#L9)).

If the error occurs about 15% of software executions, it's because you haven't defined a random seed: the `train_test_split` function doesn't produce the same split in your data and so some toxic data isn't in your calibration set.

```python
random_state = 42

train, calib = train_test_split(data, test_size=0.25, shuffle=True, random_state=random_state)
```

After all, I could assume that some of your data is extremely small or large compared to the computer precision and that this causes problems in the consistency check.

# Resolution of the exception
But don't worry, because the method proposed by MAPIE is mathematically valid, and this is an extreme error involving computer precision, we can manually remove this check. Here's the code to do just that: 
```python
from mapie.conformity_score import AbsoluteConformityScore

my_conformity_score = AbsoluteConformityScore()
my_conformity_score.consistency_check = False

mapie = MapieRegressor(model, cv="prefit", conformity_score=my_conformity_score)
```

# Conclusion
I admit I've never seen this kind of exception raised in this kind of situation. This is why the way to solve the issue is not aesthetic. But this issue could be the subject of a future readjustment to more easily control this parameter as soon as the object is initialised.

I hope I've been able to help you solve your issue. Don't hesitate to let me know if the solution works for you.

**Comment by jesuinovieira** [comment]
Thanks a lot for the thorough explanation, @thibaultcordier :) I really appreciate it! I was wondering if disabling the consistency check could potentially have any other effects during execution. However, if everything remains mathematically valid, then I'm fine with it.
