### ISSUE TITLE
Using MAPIE with transformer based models

### ISSUE THREAD

**Issue by vahuja4** [scikit-learn-contrib/MAPIE#340]
My question is simple: is it possible to use MAPIE for transformer based models from lets say huggingface? Thank you!

**Comment by thibaultcordier** [comment]
Hello @vahuja4,

- The answer is yes, you can use MAPIE for any model that is compatible with or integrated into the scikit-learn API.
- In your particular example, it is possible to use MAPIE for transformer-based models if you adapt your model to the scikit-learn API with a wrapper (to define `train` and`predict` methods as in scikit-learn).

## A detailed proposal for using MAPIE for a non-scikit-learn model
Here I detail the steps involved in integrating your model into the scikit-learn API. For the example, I'm proposing an image classification model wrapper based on Tensorflow/Keras, but it works equally well for any model and any task depending on the particular framework you're using (in your case tansformer/huggingface).

### Import

```python
from typing import List, Tuple

import numpy as np

import tensorflow.keras as tfk
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPooling2D
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.optimizers import Adam

from mapie.classification import MapieClassifier
```

### Step 1: Define our model

You define your model as usual. In this example, I'm building a CNN with Tensforflow/Keras.

```python
def get_model(
    input_shape: Tuple, loss: tfk.losses,
    optimizer: tfk.optimizers, metrics: List[str]
) -> Sequential:
    model = Sequential([
        Conv2D(
            input_shape=input_shape,
            filters=16,
            kernel_size=(3, 3),
            activation='relu',
            padding='same'
        ),
        MaxPooling2D(pool_size=(2, 2)),
        Conv2D(
            input_shape=input_shape,
            filters=32,
            kernel_size=(3, 3),
            activation='relu',
            padding='same'
        ),
        MaxPooling2D(pool_size=(2, 2)),
        Conv2D(
            input_shape=input_shape,
            filters=64,
            kernel_size=(3, 3),
            activation='relu',
            padding='same'
        ),
        MaxPooling2D(pool_size=(2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(10, activation='softmax'),
    ])
    model.compile(loss=loss, optimizer=optimizer, metrics=metrics)
    return model


tf_model = get_model(
    input_shape=(32, 32, 3), 
    loss=CategoricalCrossentropy(), 
    optimizer=Adam(), 
    metrics=['accuracy']
)
```

### Step 2: Define our wrapper

Our goal now is to define a wrapper for our model that allows MAPIE to use it like any other scikit-learn model. To do this, we need to create a class that defines `fit`, `predict`, `predict_proba` and `_sklearn_is_fitted_` attributes for the model.

Good to know: You can also inherit your class with `BaseEstimator`, `RegressorMixin` or `ClassifierMixin` from scikit-learn depending on the context.

```python
class TensorflowToMapie():
    """
    Class that aimes to make compatible a tensorflow model
    with MAPIE. To do so, this class create fit, predict,
    predict_proba and _sklearn_is_fitted_ attributes to the model.
    """
    def __init__(self, model: Sequential) -> None:
        self.model = model
        self.pred_proba = None
        self.trained_ = False

    def fit(self, X_train: np.ndarray, y_train: np.ndarray) -> None:
        early_stopping_monitor = EarlyStopping(
            monitor='val_loss',
            min_delta=0,
            patience=10,
            verbose=0,
            mode='auto',
            baseline=None,
            restore_best_weights=True
        )
        self.model = self.model.fit(
            X_train, y_train, 
            batch_size=64,
            epochs=20, callbacks=[early_stopping_monitor]
        )
        self.trained_ = True
        self.classes_ = np.arange(model.layers[-1].units)

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        preds = self.model.predict(X)
        return preds

    def predict(self, X: np.ndarray) -> np.ndarray:
        pred_proba = self.predict_proba(X)
        pred = (pred_proba == pred_proba.max(axis=1)[:, None]).astype(int)
        return pred

    def __sklearn_is_fitted__(self):
        if self.trained_:
            return True
        else:
            return False

tf_wrapped_model = TensorflowToMapie(tf_model)
```

### Step 3: Fit and predict

Now you can use your model directly with MAPIE, since it's a scikit-learn model. In this case, you have two options:
- You can use `cv="prefit"` if you want to train your model outside the MAPIE routine (recommended if your model is large and you don't want to re-train it).
```python
tf_wrapped_model.fit(model, X_train, y_train)

mapie_model = MapieClassifier(estimator=tf_wrapped_model, method="plus", cv="prefit", random_state=42) 
mapie_model.fit(X_calib, y_calib)

y_preds, y_pss = mapie_model.predict(X_test, alpha=0.05)
```

- You can use `cv="split"` if you want to train and calibrate your model inside the MAPIE routine (recommended if your model is not yet trained and you want to do both at the same time).
```python
mapie_model = MapieClassifier(estimator=tf_wrapped_model, method="plus", cv="split", random_state=42) 
mapie_model.fit(X_train_and_calib, y_train_and_calib)

y_preds, y_pss = mapie_model.predict(X_test, alpha=0.05)
```

- You can use `cv=5` or any other k-fold number if you want to do cross-validation (not recommended if your model is large).

## Conclusion
I hope this answer helps you to use MAPIE for transformer-based models in the way you want. Please let me know if this answer satisfies you.

**Comment by vahuja4** [comment]
Thank you! This is very helpful.

**Comment by DhavalRepo18** [comment]
@vahuja4 can this be a made part of the library.

**Comment by LacombeLouis** [comment]
> @vahuja4 can this be a made part of the library.

Hey @DhavalRepo18, @vahuja4,
This is not in the roadmap for us at the moment. But we encourage any PR's and if you need any help, do not hesitate to contact someone in the team!
Thank you!

**Comment by thibaultcordier** [comment]
A customized wrapping solution was proposed to answer the initial question. In this way, the issue can be closed as completed.
