### ISSUE TITLE
Unable to reach the target coverage for the Jackknife after bootstrap method even on the exoplanet notebook

### ISSUE THREAD

**Issue by AlexisVignard-hub** [scikit-learn-contrib/MAPIE#367]
Hello

I've tried to use the Jackknife after bootstrap method on different datasets, and I can't reach the target coverage (i.e., 0.95 for an uncertainty specified at 0.05 with the alpha parameter). At first I thought that there must be a problem with my data (violation of the exchangeability assumption, for example), or that I'd made a mistake somewhere in my code.

I then tried to reproduce the exact same example presented on MAPIE for the exoplanet dataset by downloading the notebook and the data available here: https://github.com/scikit-learn-contrib/MAPIE/blob/master/notebooks/regression/exoplanets_mass.csv (same data, same model), and indeed the coverage is approximately 0.8 for most alpha thresholds and not 0.95 as indicated on the example.

**I'd like to know if other people have encountered this problem, and if it's due to an error on my part or a problem in the implementation of the MAPIE method?**

To Reproduce this problem, you only have to use Jackknife after bootstrap method on any dataset and display the coverage of the intervals.
You can also check the official MAPIE notebook https://github.com/scikit-learn-contrib/MAPIE/blob/master/notebooks/regression/exoplanets.ipynb , download and run it with the exoplanet data (sent on the link above) to compare how Jackknife after bootstrap differs from the notebook and your results.

Here is the official coverage plot, where you can see Jackknife after bootstrap in purple (also available at the bottom of the official notebook) which reach the target coverage: 

![image](https://github.com/scikit-learn-contrib/MAPIE/assets/91522224/e0055dcc-5bd2-468a-be5c-be1d2a727bfa)

**Here is what I obtain by downloading and running this exact same notebook:** 

![image](https://github.com/scikit-learn-contrib/MAPIE/assets/91522224/e2c99b6d-3095-4a86-b885-8c67ca796d95)

Best regards,
Alexis

**Comment by thibaultcordier** [comment]
Hello @AlexisVignard-hub, thank you for reporting this bug. I will investigate the issue as soon as possible and get back to you to explain the reasons for your observations.

**Comment by AlexisVignard-hub** [comment]
Hello @thibaultcordier, Thank you very much for your very detailed answer.

The proposed solution does indeed work, and I would like to know if any research has been carried out on the subject of the size of these sub-samples, as well as their number.

The exoplanet dataset contains approximately 2300 lines, and here dividing the training set by 10 seems efficient. But what about much larger data sets and much smaller data sets?

From the few tests I've been able to carry out, it seems that dividing the training set by 10 is an acceptable rule, and I'd like to know if your choice of dividing the train set by 10 comes from a theoretical basis?

Best regards
Alexis

**Comment by thibaultcordier** [comment]
The Jackknife after bootstrap method was proposed in the following paper: [Kim, B., Xu, C., & Barber, R. (2020). Predictive inference is free with the jackknife+-after-bootstrap. Advances in Neural Information Processing Systems, 33, 4138-4149.](https://proceedings.neurips.cc/paper/2020/file/2b346a0aa375a07f5a90a344a61416c4-Paper.pdf). We drew inspiration from this article to implement it in MAPIE.

Unfortunately, I don't have any references to share with you (or at least I'm not aware of any) regarding the research that has been carried out into the size and number of these sub-samples.

However, the intuition is as follows:
- first, let's define `n_resamplings` the number of resamplings, `n_samples` the number of samples in each resampling and `n_data` the total number of examples.
- using the standard cross-validation cross-conforming method (`"cv_plus": Params(method="plus", cv=n_resamplings)`), we divide the training dataset into `n_resamplings` folds with `n_data/n_resamplings` samples in each fold.
- defining `n_samples=n_data/n_resamplings` with the jackknife method after bootstrapping (`"jackknife_plus_ab": Params(method="plus", cv=Subsample(n_resamplings=n_resamplings, n_samples=n_data/n_resamplings))`) gives you behaviour similar to the cross-validation method, but with a replacement of your samples (technically because you're not generating a perfect partition of your training dataset).
- if you define `n_samples>n_data/n_resamplings`, you increase the number of examples shared between all the resamplings and therefore reduce the number of calibration data. You increase the overfitting of your model on training/calibration data, which deteriorates the quality of the estimate of the distribution of non-conformity scores (but the good thing is that you increase the performance of your predictive models because you use more data for training).
- If you define `n_samples<n_data/n_resamplings`, you increase the number of examples which are not in any resamplings and therefore these data will be systematically used as calibration data and thus avoid over-fitting, which improves the quality of the estimate of the distribution of non-conformity scores (but deteriorates the performance of your predictive model).

So it's a trade-off between the performance of your predictive model and the quality of your model calibration.

My choice to divide the training set by 10 comes from an intuitive/practical basis, and is therefore more appropriate to the exoplanet dataset (here, I choose `n_resamplings=5`, and `n_samples=n_data/(2*n_resamplings))`to increase the amount of calibration data not used for training).

I hope I've been able to give you a satisfactory answer to your question.

Best regards,
Thibault

**Comment by AlexisVignard-hub** [comment]
Thank you for your answer! This is very clear and helpful.

Best regards,
Alexis
