### ISSUE TITLE
ModuleNotFoundError: No module named 'mapie.conformity_scores.residual_conformity_scores' 

### ISSUE THREAD

**Issue by gaspardc-met** [scikit-learn-contrib/MAPIE#511]
Hello MAPIE team
Been happily using MAPIE for a while now. Filling this because I'm not sure if the regression is intended from the `0.9.0` release or not.

**Describe the bug**
Failing to load previously trained MAPIE models

```python
ModuleNotFoundError: No module named 'mapie.conformity_scores.residual_conformity_scores'
 ```

**To Reproduce**
- Trained MapieRegressor instanced over LinearRegression and RandomForest using `MAPIE==0.8.4`
- Pickled them with joblib
- Loading them to memory again with `MAPIE < 0.9.0` (up to 0.8.6) works fine 
- With MAPIE 0.9.0 I get this error: ModuleNotFoundError: No module named 'mapie.conformity_scores.residual_conformity_scores' 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu on WSL Windows 11
 - Browser Firefox
 - MAPIE Version work with 0.8.6, breaks with 0.9.0
 - Python version: tested with 3.12.5

**Additional context**

**Comment by thibaultcordier** [comment]
Hi @gaspardc-met, thanks for your message and glad to hear you've been using MAPIE for a while.

### Explanation of the bug
This bug is a direct consequence of the renaming of certain files (the `mapie/conformity_scores/residual_conformity_scores.py` file no longer exists, but the `ResidualNormalisedScore` class still exists and can be accessed from the `mapie.conformity_scores` module).

### Suggested solution
At this stage, you can resolve this bug simply by updating the new path to the class, directly in the `conformity_scores` module, like this:

```python
from mapie.conformity_scores import ResidualNormalisedScore
```

### Conclusion

Even with the update to MAPIE, you can still access all the existing functions and classes. Their access path has just changed (surely we should have left the previous access path still operational for the time of the update).

Don't hesitate to let me know if this solution solves your problem.

**Comment by gaspardc-met** [comment]
Thank you for the feedback @thibaultcordier 

To be honest the models are in production so for now I just pinned MAPIE to <0.9.0 to avoid retraining them. 
I will watch out for the patch and the next releases to upgrade 👍

**Comment by vincentblot28** [comment]
Hello @gaspardc-met, we have just merged the PR which fixes your issue and released a new version of mapie (0.9.1) on pypi. The conda version should be available in one our two days ! We hope that this fix will solve your problems !

**Comment by vincentblot28** [comment]
Mapie version 0.9.1 is now also available on conda !

**Comment by gaspardc-met** [comment]
Hi @vincentblot28 ,

Thank you for the patch and the heads-up. 
I have upgraded MAPIE to 0.9.1, and it works without updating the models. 

Best regards
